### ISSUE TITLE
Variable results in nucleotide searches

### ISSUE THREAD

**Issue by jmeppley** [hallamlab/LAST-Plus#3]
Nucleotide searches are not returning the correct results in all cases and return different results depending on other sequences in the query file.

Here is a simple example using Silva release 123. I made fasta files of the first 1, 10, and1000 SSU rRNA entries. I created a database with of the 1000 sequences with lastdb+:

```
lastdb+ test.1000.ldb test.1000.fasta
```

Then I queried the database using the files with 1 and 10 sequences:

```
for N in 1 10; do
 lastal+ -S 50 -K 5 -P 18 -f 2 -o test.$N.silva1000.S50.K5.P18.f2.lastn test.1000.ldb test.$N.fasta; 
done
```

The results for the single sequence in test.1.fasta are different in the test.10 results:

```
[jmeppley SSU]$ grep HP451749.6.1794 test.1.silva1000.K2.P18.f2.lastn  test.10.silva1000.K2.P18.f2.lastn
test.1.silva1000.K2.P18.f2.lastn:HP451749.6.1794        HP451749.6.1794 100    1789     0       0       0       1789    0       1789    0       2.83e+03
test.1.silva1000.K2.P18.f2.lastn:HP451749.6.1794        AB011018.1.1740 94     1642     81      6       36      1682    0       1642    0       2.25e+03
test.10.silva1000.K2.P18.f2.lastn:HP451749.6.1794       AB018131.1.1762 80     1646     271     27      19      1676    0       1646    0       1.47e+03
test.10.silva1000.K2.P18.f2.lastn:HP451749.6.1794       AB018163.1.1750 81     1632     226     47      1       1676    1       1633    0       1.47e+03
```

Only in the test.1 results does the sequence match to itself.

You can find the test files on DropBox:
https://www.dropbox.com/sh/zbetuf6mv5k3d0c/AABdULNT6VFeqwy2BIMuxhPZa?dl=0

**Comment by jmeppley** [comment]
PS: These Silva files are the smallest set I could reproduce the problem on, but I originally found it querying a database of predicted coding sequences with illumina reads.

**Comment by dongjaek** [comment]
Hi John, I'll look into it.

**Comment by nielshanson** [comment]
Hey John,

After a bit of tracing of the code, we discovered that the inconsistency was due to the results not having nice ordering for very small E-values. The results are sorted first by query name then by E-value. However, if the e-value is identical (i.e., 0) than the ordering is uncertain. We fixed this by further sorting the results based on bitscore.

Try out this commit (2ddc9ab) and let us know if the issue is corrected on your end.

Cheers,
Niels

**Comment by jmeppley** [comment]
It solves the problem with my Silva test case but I'm still seeing weird things on my real data:

The test files:

```
$ cat test.fasta
>NS500472:23:HH75WBGXX:1:11101:10127:7535 1:N:0:ATCACG
AGTCTGGGGGTAATGAGTTTTCAGGCTCAATGCTGGAAACAGGATTAAGTCTAAATCGTG
TTACAACTGTTAGAGAACAGATGCTGGAAGGGTGAAGATCCTTGGATCGTAACCAGGAAA
GTATCGGCAGGG

$ cat test.n1.fasta
>NS500472:23:HH75WBGXX:1:11101:10127:7535 1:N:0:ATCACG
AGTCTGGGGGTAATGAGTTTTCAGGCTCAATGCTGGAAACAGGATTAAGTCTAAATCGTG
TTACAACTGTTAGAGAACAGATGCTGGAAGGGTGAAGATCCTTGGATCGTAACCAGGAAA
GTATCGGCAGGG
>NS500472:23:HH75WBGXX:1:11101:25115:1119:ATCACG
TGTGTGGTTTGGGGTGGGATGTCTCAGAATCGAAAGGGCTTTTTGGACTTTTTAAAGCCA
ATGATTTTGATCTCGATGCGTCTGTTTTATGTTTAACCAATAAAGATAAATTAAAGAGTA
AATCTGATGTGGTTTACTATAGAAACCTGGAGCATTCATCAGGAGCAATTACTCATCAAG
GAGATAACTTAACAGGGTAAGG
>NS500472:23:HH75WBGXX:1:11101:24009:1251:ATCACG
TGTGTAGAGCAAGCTGACTATCTTTAGCTGGGTTGTGAGATTGTCCAGTCACATGGGAGC
TGAAAAACATCCCACCGTTGGCAGCAGTGGAGAATATTGGTCAATGAACGAAAGTTTGAA
CCAGCATTTCGCGTAAAATGATAGGCCTAATAACTTAGGCCACGAAGGCTATGAG
>NS500472:23:HH75WBGXX:1:11101:23341:1292:ATCACG
ATGCAGAGAGTTAGTAAACCTGGTTTGAGAATTTATAAAAATACTAAGGGTTTACCAAAA
GTTCTTGGAGGtcttggagTTGCTATAATTTCAACTTCTAAAGGCGTTATGAGTGATCGC
GATGCGAGGAAGCAAGGCATTGGCGGCGAAGTCCTCTGCTATGTTTATTAAGGAGAATTA
ATCATGACAAGA
```

...give the following output (filtered for read NS500472:23:HH75WBGXX:1:11101:10127:7535):

```
./test.fasta
NS500472:23:HH75WBGXX:1:11101:10127:7535    HOT226_1_0025m_rep_c78314_1 98  103 2   0   29  132 0   103 6.3391e-46  151
./test.n1.fasta
NS500472:23:HH75WBGXX:1:11101:10127:7535    HOT236_1_0125m_c201809_2    68  167 53  0   25  192 214 381 7.8982e-29  107
NS500472:23:HH75WBGXX:1:11101:10127:7535    HOT236_1_0025m_rep_c314465_1    92  56  4   0   52  108 0   56  3.7363e-18  73
NS500472:23:HH75WBGXX:1:11101:10127:7535    HOT233_2_0025m_rep_c570444_3    78  55  12  0   105 160 347 402 8.893e-17   69
```

The single hit returned  in the first case is the answer returned by the conventional lastal. 

I'm currently downloading and formatting some RefSeq proteins to see if I can reproduce on a smaller scale...

**Comment by dongjaek** [comment]
Hi John,

this is likely because in LAST+ we use bit-score and bit-evalue. Using parameters representing the database's composition and size we normalized the score and evalue to produce a bit-score and bit-evalue which are more comparable across different databases. 
This will lead to a potential different ordering from the original LAST but we stand behind our method as it is the standard across all modern aligners to normalize score and evalue and we have used the same normalization scheme that BLAST and most modern aligners share.

The following link explains the evalue and score normalization in more depth.
http://www.ncbi.nlm.nih.gov/BLAST/tutorial/

If you are happy with current state of the software regarding this problem, let us know so we can resolve this issue.

**Comment by jmeppley** [comment]
It's not a different ordering, it's different results. The original last only finds one result. Last+ sometimes finds that result, and sometimes finds 3 entirely different (not as good) results. The only difference between the two runs of last+ was the number of reads in the query.

Once I find another test set, I'll pass it on.
